server:
  port: 88

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    gateway:
      routes:
        - id: treat
          uri: http://localhost:88
          predicates:
            - Path=/Biosan/Treat/**
          filters:
            - RewritePath=/Biosan/(?<segment>.*),/$\{segment}

        - id: acme
          uri: http://localhost:88
          predicates:
            - Path=/Biosan/Acme/**
          filters:
            - RewritePath=/Biosan/(?<segment>.*),/$\{segment}
    sentinel:
      eager: true #启动立即加载初始化, 而不是有流量之后再和控制台交互
      transport:
        port: 8719
        dashboard: 172.17.90.244:8091
        heartbeat-interval-ms: 15000
      # 路由的配置可以做持久化到数据库
      datasource:
        ds:
          nacos: # 整合nacos,把流控规则保存到nacos, sentinel控制台启动时候就能够读取这个配置
            #            server-addr: 172.17.90.244:8848,172.17.91.23:8848,172.17.90.55:8848
            server-addr: 172.17.90.244:8848
            dataId: gateway-sentinel-flow # 为什么会这样设置，后面会讲到
            namespace: public
            groupId: sentinel-dev
            rule-type: gw_flow # 流控配置
            data-type: json
        ds2:
          nacos:
            server-addr: 172.17.90.244:8848
            dataId: gateway-sentinel-degrade
            namespace: public
            groupId: sentinel-dev
            rule-type: DEGRADE # 流控配置
            data-type: json
security:
  enable: false
rsa:
  public-key: classpath:/rsa.pub

logging:
  level:
    org.springframework.cloud.gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: '*' #shutdown,health,info,loggers,gateway,sentinel